# See http://www.appveyor.com/docs/appveyor-yml for many more options

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.4.{build}

branches:
  only:
    - master

#skip_commits:
#  files:
#    - '**/*.md'

only_commits:
  files:
    - src/


#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

# environment variables
environment:
  GithubAuthToken:
    secure: wOVgzCOe1WC8W7wF1RfAsCS19jCVEIoYwqL+cQvW90O50JDaCGVIwmf9nN89uM8L

# scripts that run after cloning repository
install:
  - ps: |
      $null = Get-PackageProvider -Name NuGet -ForceBootstrap
      if ((Get-PSRepository -Name PSGallery).InstallationPolicy -ne 'Trusted') {
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
      }
      Install-Module Psake, PSDeploy, BuildHelpers, platyPS, PSScriptAnalyzer -Force -AllowClobber -Scope CurrentUser
      Install-Module Pester -MinimumVersion 4.4 -Force -AllowClobber -SkipPublisherCheck -Scope CurrentUser


#---------------------------------#
#       build configuration       #
#---------------------------------#

# to disable automatic builds
# build: off

# to run your custom scripts instead of automatic MSBuild
build_script:
  - ps: . .\Build.ps1


#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic tests
test_script:
  - ps: |
      $TestFile =  Join-Path -Path $env:BHBuildOutput -ChildPath "testoutput.xml"
      Invoke-Pester -OutputFormat NUnitXml -OutputFile $TestFile
      (New-Object 'System.Net.WebClient').UploadFile(
          "https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)",
          $TestFile )


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: Release/$(BHProjectName)
#  - type: Zip

#deploy:
#  - provider: GitHub
#    auth_token: $(GithubAuthToken)
#    draft: true
#    prerelease: false
#    on:
#      branch: master          # release from master branch only
#      appveyor_repo_tag: true # deploy on tag push only
