# See http://www.appveyor.com/docs/appveyor-yml for many more options

version: 1.4.{build}

os: WMF 5

branches:
  only:
    - master

skip_commits:
  files:
    - README.md
    - CHANGELOG.md

install:
  - ps: |
      $null = Get-PackageProvider -Name NuGet -ForceBootstrap
      if ((Get-PSRepository -Name PSGallery).InstallationPolicy -ne 'Trusted') {
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
      }
      Install-Module Psake, PSDeploy, BuildHelpers, platyPS -Force -AllowClobber -Scope CurrentUser
      Install-Module Pester -MinimumVersion 4.4 -Force -AllowClobber -SkipPublisherCheck -Scope CurrentUser


# to disable automatic builds
# build: off

build_script:
  - ps: . .\Build.ps1

test_script:
  - ps: |
      $TestFile =  Join-Path -Path $env:BHBuildOutput -ChildPath "testoutput.xml"
      Invoke-Pester -OutputFormat NUnitXml -OutputFile $TestFile
      (New-Object 'System.Net.WebClient').UploadFile(
          "https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)",
          $TestFile )

artifacts:
  - path: release\PWAddins
  - type: zip

#deploy:
#  - provider: GitHub
#    auth_token: $(GithubAuthToken)
#    draft: false
#    prerelease: false
#    on:
#      branch: master
#      appveyor_repo_tag: true

